[package]
name = "pong"
version = "0.1.0"
authors = ["Marc Partensky <marc.partensky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.5"
rand = "0.7.3"
